'use client';
import React, { useState, useEffect } from 'react';
import StatCard from '@/components/ui/StatCard';
import Table from '@/components/ui/Table';
import Button from '@/components/ui/Button';
import Modal from '@/components/ui/Modal';
import Input from '@/components/ui/Input';
import SkeletonLoader from '@/components/ui/SkeletonLoader';
import { DollarIcon, PatientsIcon, CheckCircleIcon, FlaskIcon, DownloadIcon } from '@/components/ui/Icons';

export default function AdminReports() {
  const [loading, setLoading] = useState(true);
  const [modalOpen, setModalOpen] = useState(false);
  useEffect(() => { const t = setTimeout(() => setLoading(false), 1500); return () => clearTimeout(t); }, []);

  const reports = [
    { name: 'Monthly Patient Report', type: 'Patients', date: '2025-04-01', by: 'Admin' },
    { name: 'Revenue Summary Q1', type: 'Financial', date: '2025-03-31', by: 'Admin' },
    { name: 'Lab Utilization Report', type: 'Laboratory', date: '2025-04-05', by: 'Admin' },
    { name: 'Staff Attendance March', type: 'HR', date: '2025-04-02', by: 'Admin' },
  ];

  if (loading) return <><div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">{[1,2,3,4].map(i => <SkeletonLoader key={i} height={100} />)}</div><SkeletonLoader height={52} count={4} /></>;

  return (
    <>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5 mb-6">
        <StatCard icon={<DollarIcon size={22} />} label="Revenue" value="KES 840,500" trend="+12% vs last month" trendUp />
        <StatCard icon={<PatientsIcon size={22} />} label="Admitted" value={32} trend="+5 this week" trendUp iconBg="var(--info-light)" iconColor="var(--info)" />
        <StatCard icon={<CheckCircleIcon size={22} />} label="Discharged" value={18} trend="+3 this week" trendUp iconBg="var(--success-light)" iconColor="var(--success)" />
        <StatCard icon={<FlaskIcon size={22} />} label="Pending Labs" value={7} trend="-2 from yesterday" trendUp iconBg="var(--warning-light)" iconColor="var(--warning)" />
      </div>

      <div className="flex items-center justify-between mb-6">
        <h3 className="text-base font-bold text-slate-800 mb-4">Generated Reports</h3>
        <Button onClick={() => setModalOpen(true)}>Generate Report</Button>
      </div>

      <Table headers={['Report Name', 'Type', 'Date Generated', 'Generated By', 'Action']}>
        {reports.map((r, i) => (
          <tr key={i}><td><strong>{r.name}</strong></td><td>{r.type}</td><td>{r.date}</td><td>{r.by}</td>
            <td><Button variant="secondary" style={{ padding: '6px 12px', fontSize: 12 }}><DownloadIcon size={14} /> Download</Button></td></tr>
        ))}
      </Table>

      <Modal open={modalOpen} onClose={() => setModalOpen(false)} title="Generate Report"
        footer={<><Button variant="secondary" onClick={() => setModalOpen(false)}>Cancel</Button><Button onClick={() => setModalOpen(false)}>Generate</Button></>}>
        <Input label="Report Type" options={[{value:'patients',label:'Patients'},{value:'financial',label:'Financial'},{value:'lab',label:'Laboratory'},{value:'hr',label:'HR'}]} />
        <div className="flex items-center justify-between gap-4 py-2 border-b border-slate-100 last:border-0">
          <Input label="From Date" type="date" />
          <Input label="To Date" type="date" />
        </div>
      </Modal>
    </>
  );
}
